# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c4a29791b89413d70b0dad49c8facce1a11ded5963a1c59c144f69e7437fdb2f141429e29a14d5caf890bddc506a5b0f41d57426e2ffca42d79c1170f2385f3

test:
  secret_key_base: 68fdf47f26af98a3f01aa50a8535d70e1b41ea84f1848e0334bae05749b9cad30a2ce03c434d862f7ef732bd545d45e9ecca8b96896acf622a4b129d228a7fb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
